name: myenv
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pytest
  - flake8

git add .github/workflows/python-package-conda.yml environment.yml
git commit -m "Add environment.yml and update workflow"
git push
