name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    # Setup Node.js 20
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Setup Python 3.8 and Conda
    - name: Set up Python 3.8 and Conda
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    # Install Miniconda
    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda3
        rm miniconda.sh

    # Configure Conda and activate environment
    - name: Configure Conda and activate environment
      run: |
        echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> $HOME/.bashrc
        source $HOME/.bashrc
        conda activate base
        conda init bash
        conda activate myenv

    # Download environment.yml (assuming this step is necessary)
    - name: Download environment.yml
      run: |
        mkdir -p .github/workflows
        curl -o .github/workflows/environment.yml -L https://github.com/lauashk/data-science-projects/raw/main/.github/workflows/environment.yml

    # Create Conda environment (if needed)
    - name: Create Conda environment
      run: |
        conda env create -f .github/workflows/environment.yml
        conda activate myenv

    # Install dependencies and run pytest
    - name: Install dependencies and run pytest
      run: |
        pip install pytest
        pytest  # Add any additional pytest options or flags here if needed

    # Check if main.js exists (if needed)
    - name: Check if main.js exists
      id: check_main_js
      run: |
        if [ -f main.js ]; then
          echo "main_js_exists=true" >> $GITHUB_ENV
        else
          echo "main_js_exists=false" >> $GITHUB_ENV
        fi

    # Run main.js if it exists (if needed)
    - name: Run main.js
      if: env.main_js_exists == 'true'
      run: node main.js
