name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    # Setup Node.js 20
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python 3.8 and Conda
      uses: actions/setup-python@v3  # Use version 3 of setup-python action
      with:
        python-version: 3.8
        architecture: 'x64'  # Specify the architecture if needed

    - name: Install Miniconda
      run: |
        # Download and install Miniconda
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda3
        rm miniconda.sh

    - name: Configure Conda
      run: |
        echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> $HOME/.bashrc

    - name: Initialize Conda
      run: |
        source $HOME/.bashrc

    - name: Download environment.yml
      run: |
        mkdir -p .github/workflows
        curl -o .github/workflows/environment.yml -L https://github.com/lauashk/data-science-projects/raw/main/.github/workflows/environment.yml

    - name: Create and Activate Conda environment
      run: |
        conda env create -n myenv -f .github/workflows/environment.yml
        echo "source $HOME/miniconda3/etc/profile.d/conda.sh" >> $GITHUB_ENV
        echo "conda activate myenv" >> $GITHUB_ENV

    - name: Lint with flake8
      run: |
        source $HOME/miniconda3/etc/profile.d/conda.sh
        conda activate myenv
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        source $HOME/miniconda3/etc/profile.d/conda.sh
        conda activate myenv
        pytest

    # Check if main.js exists (if needed)
    - name: Check if main.js exists
      id: check_main_js
      run: |
        if [ -f main.js ]; then
          echo "main_js_exists=true" >> $GITHUB_ENV
        else
          echo "main_js_exists=false" >> $GITHUB_ENV
        fi

    # Run main.js if it exists (if needed)
    - name: Run main.js
      if: env.main_js_exists == 'true'
      run: |
        node main.js
