name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    # Setup Node.js 20
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python 3.8
      uses: actions/setup-python@v2  # Updated to use version 2 of setup-python action
      with:
        python-version: 3.8

    - name: Download environment.yml
      run: |
        mkdir -p .github/workflows
        curl -o .github/workflows/environment.yml -L https://github.com/lauashk/data-science-projects/raw/main/.github/workflows/environment.yml

    - name: Add conda to system path
      run: |
        echo "$HOME/miniconda3/bin" >> $GITHUB_PATH

    - name: Create conda environment
      run: |
        conda env create -f .github/workflows/environment.yml  # Use `conda env create` instead of `conda env update`
        conda activate base  # Activate the environment

    - name: Lint with flake8
      run: |
        pip install flake8  # Install flake8 using pip within the activated environment
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

    # Check if main.js exists (if needed)
    - name: Check if main.js exists
      id: check_main_js
      run: |
        if [ -f main.js ]; then
          echo "main_js_exists=true" >> $GITHUB_ENV
        else
          echo "main_js_exists=false" >> $GITHUB_ENV
        fi

    # Run main.js if it exists (if needed)
    - name: Run main.js
      if: env.main_js_exists == 'true'
      run: node main.js
