name: Python Package with Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8 and Conda
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda3
          rm miniconda.sh
          source $HOME/miniconda3/etc/profile.d/conda.sh
          conda init bash  # Ensure conda is properly initialized

      - name: Create and Activate Conda Environment
        run: |
          source $HOME/miniconda3/etc/profile.d/conda.sh
          conda env create -f .github/workflows/environment.yml  # Assuming environment.yml exists in your repo
          conda activate myenv  # Assuming your env name is myenv (change if different)
          conda install pytest  # Install testing tools in the environment
          pip install flake8   # Install flake8 using pip within the environment

      - name: Activate Conda Environment
        run: |
          source $HOME/miniconda3/etc/profile.d/conda.sh
          conda activate myenv

      - name: Lint with flake8
        run: |
          source $HOME/miniconda3/etc/profile.d/conda.sh
          conda activate myenv
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Show directory structure for debugging
        run: |
          echo "Directory structure:"
          find .

      - name: Test with pytest
        run: |
          source $HOME/miniconda3/etc/profile.d/conda.sh
          conda activate myenv
          pytest --maxfail=5 --disable-warnings -v

      # Run main.js if it exists (optional)
      - name: Check if main.js exists
        id: check_main_js
        run: |
          if [ -f main.js ]; then
            echo "main_js_exists=true" >> $GITHUB_ENV
          else
            echo "main_js_exists=false" >> $GITHUB_ENV
          fi

      - name: Run main.js
        if: env.main_js_exists == 'true'
        run: |
          node main.js
